name: build-images

on:
  push:
    branches:
      - 'main'

jobs:
  list-changed-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-changed-images.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed file's directories
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'

      - name: List changed image directories
        id: list-changed-images
        run: echo "matrix=$(find ${{ steps.changed-files.outputs.all_modified_files }} -type f -name Dockerfile -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-image:
    needs: list-changed-images
    runs-on: ubuntu-latest
    strategy:
        matrix:
            image: ${{ fromJson(needs.list-changed-images.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Read rolling tags
        id: rolling-tags
        uses:  mikefarah/yq@v4
        with:
          cmd: yq eval '.rolling-tags[]' ./${{ matrix.image }}/tags-info.yaml
