name: build-images

on:
  push:
    branches:
      - 'main'

jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files in the image folder
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'

      - name: see the output
        run: echo ${{ steps.changed-files.outputs.all_modified_files }}

      # - name: List all image folders
      #   id: list-all-images
      #   run: echo "all-images=$(find . -type f -name Dockerfile -exec dirname {} \; | sed 's|^\./||')" >> $GITHUB_OUTPUT

      # - name: Get changed files in the image folder
      #   id: changed-files-specific
      #   uses: tj-actions/changed-files@v44
      #   with:
      #     files: |
      #       ${{ steps.list-all-images.outputs.all-images }}



  # build-image:
  #   needs: list-changed-files
  #   runs-on: ubuntu-latest
  #   strategy:
  #       matrix:
  #           image: ${{ fromJson(needs.list-dockerfiles.outputs.matrix) }}
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Read rolling tags
  #       id: rolling-tags
  #       uses:  mikefarah/yq@v4
  #       if: steps.changed-files-specific.outputs.any_changed == 'true'
  #       with:
  #         cmd: yq eval '.rolling-tags[]' ./${{ matrix.image }}/tags-info.yml
