name: build-images

on:
  push:
    branches:
      - 'main'

jobs:
  list-changed-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-changed-images.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed file's directories
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'

      - name: List changed image directories
        id: list-changed-images
        run: echo "matrix=$(find ${{ steps.changed-files.outputs.all_modified_files }} -type f -name Dockerfile -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: list-changed-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
        matrix:
            image: ${{ fromJson(needs.list-changed-images.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Read image info
        id: image-info
        uses: mikefarah/yq@v4
        with:
          cmd: |
            echo "name=$(yq eval '.name' ${{ matrix.image }}/image-info.yaml)" >> $GITHUB_OUTPUT \
            echo "rolling-tags=$(yq eval '.rolling-tags[]' ${{ matrix.image }}/image-info.yaml)" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.image-info.outputs.name }}
          tags: |
            ${{ steps.image-info.outputs.rolling-tags }}
            type=sha

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
